version: '3.4'

services:
  database:
    image: "${REGISTRY_NAME}mongo:4.4.6-bionic"
    volumes:
      - clubdb:/data/db
    networks:
      - "internal"
    restart: "unless-stopped"
  dashboard:
    build: .
    image: "${REGISTRY_NAME}devclubiitd/dashboard:0.1"
    ports:
      - ${PORT}:${PORT}
    restart: "unless-stopped" 
    networks:
      - "internal"
      - "reverseproxy"
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST
      - MONGODB_URI_LOCAL
    depends_on:
      - database

volumes:
  clubdb:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
